# Generated by Django 5.2.8 on 2025-11-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='noaa_alerts',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('area_desc', models.TextField()),
                ('event', models.CharField(max_length=255)),
                ('headline', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('instruction', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('message_type', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('severity', models.CharField(max_length=50)),
                ('certainty', models.CharField(max_length=50)),
                ('urgency', models.CharField(max_length=50)),
                ('sent', models.DateTimeField()),
                ('effective', models.DateTimeField()),
                ('onset', models.DateTimeField(blank=True, null=True)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('ends', models.DateTimeField(blank=True, null=True)),
                ('sender_name', models.CharField(help_text='The name of the NWS office that sent the alert.', max_length=255)),
                ('geocode', models.JSONField(default=dict)),
                ('parameters', models.JSONField(default=dict)),
            ],
        ),
    ]
