# Generated by Django 5.2.8 on 2025-11-18 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoaaAlert',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('area_desc', models.TextField()),
                ('event', models.CharField(max_length=255)),
                ('headline', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('instruction', models.TextField(blank=True, null=True)),
                ('response', models.CharField(blank=True, max_length=50, null=True)),
                ('affected_zones', models.JSONField(default=list)),
                ('geometry', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(max_length=50)),
                ('message_type', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('severity', models.CharField(max_length=50)),
                ('certainty', models.CharField(max_length=50)),
                ('urgency', models.CharField(max_length=50)),
                ('sent', models.DateTimeField()),
                ('effective', models.DateTimeField()),
                ('onset', models.DateTimeField(blank=True, null=True)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('ends', models.DateTimeField(blank=True, null=True)),
                ('sender_name', models.CharField(help_text='the name of the nws office that sent the alert.', max_length=255)),
                ('geocode', models.JSONField(default=dict)),
                ('parameters', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='StormEvent',
            fields=[
                ('event_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=100)),
                ('begin_year', models.IntegerField(default=1)),
                ('begin_month', models.IntegerField(default=1)),
                ('end_year', models.IntegerField(default=1)),
                ('end_month', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='AlertNotificationTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.noaaalert')),
            ],
        ),
        migrations.CreateModel(
            name='UserAreaSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('notification_type', models.CharField(choices=[('new', 'notify on new alert'), ('update', 'notify on update'), ('expires', 'notify before expiry'), ('all', 'all notification options')], default='new', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
