# Generated by Django 5.2.8 on 2025-11-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stormevent',
            name='begin_time',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stormevent',
            name='end_time',
            field=models.IntegerField(default=1),
        ),
    ]
