# Generated by Django 5.2.8 on 2025-11-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noaa_alerts',
            name='affected_zones',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='noaa_alerts',
            name='geometry',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='noaa_alerts',
            name='response',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
