# Generated by Django 5.2.8 on 2025-11-20 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_stormevent_begin_time_stormevent_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userareasubscription',
            name='county',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userareasubscription',
            name='notification_type',
            field=models.CharField(choices=[('new', 'Notify on new alert'), ('update', 'Notify on update'), ('expires', 'Notify before expiry'), ('all', 'All notifications')], default='new', max_length=50),
        ),
    ]
