# Generated by Django 5.2.8 on 2025-11-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_noaa_alerts_affected_zones_noaa_alerts_geometry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noaa_alerts',
            name='geometry',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
