# Generated by Django 5.2.8 on 2025-11-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_userareasubscription_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userareasubscription',
            name='state',
            field=models.CharField(default='', max_length=255),
        ),
    ]
