# Generated by Django 5.2.8 on 2025-11-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_userareasubscription_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='userareasubscription',
            name='carrier',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
