# Generated by Django 5.2.8 on 2025-11-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_userareasubscription_carrier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noaaalert',
            name='sender_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userareasubscription',
            name='notification_type',
            field=models.CharField(choices=[('New', 'Notify on new alert'), ('Update', 'Notify on update'), ('Expires', 'Notify before expiration'), ('All', 'All notifications')], default='new', max_length=50),
        ),
    ]
