# Generated by Django 5.2.8 on 2025-11-17 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_user_area_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='storm_event',
            fields=[
                ('event_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=100)),
            ],
        ),
    ]
