# Generated by Django 5.2.8 on 2025-11-17 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_storm_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='storm_event',
            name='begin_month',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storm_event',
            name='begin_year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storm_event',
            name='end_month',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storm_event',
            name='end_year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
