# Generated by Django 5.2.8 on 2025-11-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_alter_noaaalert_sender_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stormevent',
            name='county_fips',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='stormevent',
            name='state_fips',
            field=models.CharField(default='', max_length=10),
        ),
    ]
