# Generated by Django 5.2.8 on 2025-12-02 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_stormevent_county_fips_stormevent_state_fips'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertnotificationtracking',
            name='alert_kind',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userareasubscription',
            name='notification_type',
            field=models.CharField(choices=[('New', 'Notify on new alert'), ('Update', 'Notify on update'), ('Expires', 'Notify before expiration'), ('All', 'All notifications')], default='New', max_length=50),
        ),
    ]
