# Generated by Django 5.2.8 on 2025-12-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0008_alertnotificationtracking_alert_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertnotificationtracking',
            name='alert_kind',
            field=models.CharField(default='New', max_length=20),
        ),
    ]
