"""
Django settings for disaster_notification project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r4dr2+e##qv1v%n9id#24^2n(s@i^k8h%h03qr&_sx+a@@fer('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# adding specific hosts and domains
ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'railway.app', 'disasternotification-production.up.railway.app', os.environ.get('HOST',''),]

# tells Django to trust requests coming from below
CSRF_TRUSTED_ORIGINS = ['https://*.railway.app', 'https://disasternotification-production.up.railway.app',]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # add app
    'notification',
    'rest_framework',
    'dj-redis-panel',
    'dj_redis_panel',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # add middleware
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'disaster_notification.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'disaster_notification.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# PostgreSQL in Railway configuration

DATABASE_URL = os.environ.get('DATABASE_URL')

# fallback to sqlite if/else statement
if DATABASE_URL:
    print("Connecting to PostgreSQL")
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
            ssl_require=True
        )
    }

else:
    print("Fall back to SQLite")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Celery/Redis configuration
CELERY_BROKER_URL = os.environ.get('REDIS_URL')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Celery beat schedule
CELERY_BEAT_SCHEDULE = {
    'fetch-weather-alerts-every-10-mins': {
        'task': 'notification.tasks.fetch_weather_alerts',
        'schedule': crontab(minute='*/10')
    },
}

# set variables for Redis information
RAILWAY_REDIS_HOST = os.environ.get('REDIS_HOST')
RAILWAY_REDIS_PORT = int(os.environ.get('REDIS_PORT', 6379))
RAILWAY_REDIS_PASSWORD = os.environ.get('REDIS_PASSWORD')

# Admin Redis Panel configuration
DJ_REDIS_PANEL_SETTINGS = {
        "ALLOW_KEY_DELETE": False,
        "ALLOW_KEY_EDIT": True,
        "ALLOW_TTL_UPDATE": True,

        "INSTANCES": {
            "default": {
                "description": "Default Redis Instance",
                "host": RAILWAY_REDIS_HOST,
                "port": RAILWAY_REDIS_PORT,
                "password": RAILWAY_REDIS_PASSWORD if RAILWAY_REDIS_PASSWORD else None,
                },
            },
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# add static root files
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = BASE_DIR / 'static',

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
